import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Box } from "@mui/material";
import Navbar from "./component/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <Box>
          <Navbar/>
        </Box> */}
        { children }
      </body>
    </html>
  );
}
